 
# Config Server AWS version
# spring:
#   application:
#     name: user-service
#   config:
#     import: "optional:configserver:http://config-service"

#   cloud:
#     config:
#       fail-fast: true



server:
    # port: 0
    port: 8080

eureka: ##
  client:
    enabled: true ### 테스트

spring:
 
    cloud: ##
        config:
            enabled: false ### 설정서버 사용 안함(테스트할때만)
    application:
        name: user-service
    
    datasource:
    # 우선은 로컬 DB사용
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/fairyTale
        username: root
        password: 1234
    
    sql:
        init:
            mode: always # 항상 sql 파일을 실행함.

    jpa:
        defer-datasource-initialization: true # hibernate가 테이블을 만든 후에 sql을 실행하도록 함.
        hibernate:
            ddl-auto: create
        
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
    data:
        redis:
            # host: redis-service
            host: localhost
            port: 6379
            password: 
            timeout: 6000ms

# jwt:
#     secret: ${JWT_SECRET}
