spring:
  application:
    name: ai-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8080}"
  cloud:
    config:
      fail-fast: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

