 
# # Config Server AWS version
# spring:
#   application:
#     name: gamification-service
#   config:
#     import: "optional:configserver:http://config-service"

#   cloud:
#     config:
#       fail-fast: true