spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# 1. H2 데이터베이스 설정 (로컬 테스트용 메모리 DB)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 2. 서버 실행 시 DB 테이블을 자동으로 만들어주는 설정
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# 3. (옵션) 쿼리 로그 보기
spring.jpa.show-sql=true