 
# Config Server AWS version
# spring:
#   application:
#     name: story-service
#   config:
#     import: "optional:configserver:http://config-service"

#   cloud:
#     config:
#       fail-fast: true


# Docker version
spring:
  application:
    name: story-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8080}"
  cloud:
    config:
      fail-fast: true